name: Build and deploy Vue.js application to AWS S3

on:
  push:
    branches: [main]


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    defaults:
      run:
        shell: bash
        working-directory: leprechaun/frontend

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - uses: actions/checkout@v3

    - name: Configure Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: node_modules caching
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm install

    - name: Run Lint
      run: npm run lint

    - name: Build
      run: npm run build

    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 sync dist/ "s3://${{ secrets.AWS_S3_STATIC_WEBSITE_BUCKET }}" --delete
        aws s3 cp dist/index.html "s3://${{ secrets.AWS_S3_STATIC_WEBSITE_BUCKET }}/index.html" --metadata-directive REPLACE --cache-control no-cache,no-store,must-revalidate,max-age=0 --content-type text/html
